name:         lexing-makes-me-feel-good
version:      0.0.0.1
github:       "nicuveo/LexingMakesMeFeelGood"
license:      BSD-3-Clause
author:       "Antoine Leblanc"
maintainer:   "nicuveo@gmail.com"
copyright:    "2025 Antoine Leblanc"

extra-source-files:
- README.md

language: GHC2021

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs
  - -Wunused-packages
  - -fhide-source-paths
  - -foptimal-applicative-do
  - -funbox-small-strict-fields

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DerivingVia
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - PackageImports
  - RecordWildCards
  - RoleAnnotations
  - StrictData
  - TypeFamilies
  - ViewPatterns

dependencies:
  - base
  - array
  - containers
  - extra
  - hashable
  - lens
  - monad-loops
  - mtl
  - text
  - transformers
  - unordered-containers

executables:
  poc:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    build-tools:
      - alex
      - happy
